### ISSUE TITLE
numpy requirements too strict

### ISSUE THREAD

**Issue by jbrownkramer** [openvinotoolkit/openvino#11532]
The pip install of openinvo requires numpy<1.20 and >=1.16.6.  However, the codebase we have built around an older version of openvino works just fine and uses numpy 1.20.1.

**Comment by jgespino** [comment]
@jbrownkramer Thanks for raising this issue. Relaxing the numpy version is something the development team is already looking into. I will keep you posted once I know more!

Ref. 70927

**Comment by jbrownkramer** [comment]
Similarly, openvino-dev requires scipy~=1.5.4, which is fairly old.

**Comment by cansik** [comment]
This is a problem for Apple silicon devices too. I have pre-built [Apple silicon wheels](https://github.com/cansik/openvino-arm) for openvino, but because of the strict numpy requirement, we have to install it ignoring the dependencies.

**Comment by qhanson** [comment]
When you install openvino, you can not install TensorFlow, and OpenCV to the same python environment due to the conflict of numpy version.

**Comment by ilya-lavrenov** [comment]
@andrei-kochin is it fixed with latest changes in versions of numpy in OV?

**Comment by andrei-kochin** [comment]
Hello @ilya-lavrenov  and others. Yes this was addressed by PR #12191

**Comment by andrei-kochin** [comment]
@MaximProshin could you please comment on scipy dependency?  any plans to bump the version to the newer one?

**Comment by p-wysocki** [comment]
@andrei-kochin @jgespino scipy is one of the dependencies which will be bumped while enabling Python 3.10 in #12578, it is still very much WIP.

**Comment by codespree** [comment]
Numpy 1.19.5 (the latest version that supports numpy<1.20 and >=1.16.6) has security issues:
https://security.snyk.io/vuln/SNYK-PYTHON-NUMPY-2321969
https://security.snyk.io/vuln/SNYK-PYTHON-NUMPY-2321970
https://security.snyk.io/vuln/SNYK-PYTHON-NUMPY-2321964
https://security.snyk.io/vuln/SNYK-PYTHON-NUMPY-2321966

Thus, Numpy v1.22.0 or higher should be supported in wheel.

**Comment by SamSamhuns** [comment]
Is the updated numpy version in requirements pushed to PyPy yet? I still get the `openvino 2022.1.0 depends on numpy<1.20 and >=1.16.6` conflict when installing with `pip install openvino` in a macOS BigSur machine with latest tf versions.

**Comment by alex77g2** [comment]
> Is the updated numpy version in requirements pushed to PyPy yet? I still get the `openvino 2022.1.0 depends on numpy<1.20 and >=1.16.6` conflict when installing with `pip install openvino` in a macOS BigSur machine with latest tf versions.

Ubuntu 20.04.1 (amd64) + pip 22.2.2 + Python 3.8.10 + openvino-dev (default = 2022.1.0) still requires numpy-1.19.5. It seems the issue still exist in default/unmodified installations.

**Comment by p-wysocki** [comment]
PR relaxing `numpy` upper bounds to `1.23.1` https://github.com/openvinotoolkit/openvino/pull/12628 has been merged into [openvinotoolkit:releases/2022/2](https://github.com/openvinotoolkit/openvino/tree/releases/2022/2) branch.
