### ISSUE TITLE
[Bug] GPU Extensions problem

### ISSUE THREAD

**Issue by wang7393** [openvinotoolkit/openvino#12377]
##### System information (version)
- OpenVINO=> :2022.1
- Operating System / Platform => :win10
- Problem classification => :GPU Extensions problem

##### Detailed description

I have implemented a GPU custom layer.  And need to read the XML configuration file from the path, and the XML configuration file configures the kernel file.  Like this: "core.set_property("GPU", { { CONFIG_KEY(CONFIG_FILE), "***.xml" } });"
But in commercial applications, XML configuration files and kernel files need to be read from memory. Whether there is a solution now?

**Comment by Iffa-Meah** [comment]
@wang7393 it's appropriate to read the files from memory as you need to access the system's hardware (GPU). This would allow the program to capture the real operating GPU hardware itself. This is crucial in the aspect of RTOS and embedded systems to work with existing hardware instead of feeding the config from other resources that might be pseudo or actually non-existent.

Are there any reason that made it infeasible for you to read those from memory?

**Comment by wang7393** [comment]
@Iffa-Meah 
I'm sorry, I don't think I made my question clear.
What I said the scenario of reading from memory is like this: Just like the model load interface, the model file can be read from the file path or from memory (for commercial applications, the original model is encrypted, the encrypted model is read into memory first, and then the decrypted model is read through the memory load interface).

And then, back to my question.
I have implemented a GPU custom layer. Contains an XML configuration file and OpenCL kernel file. In engineering, OpenVino currently only provides such an interface for reading XML configuration files: 
` "core.set_property("GPU", { { CONFIG_KEY(CONFIG_FILE), "***.xml" } });"  `
And the XML file indicates the path to the kernel file:
![image](https://user-images.githubusercontent.com/29936604/182502318-90b4321f-72e1-4a59-aa5e-266ca0c1dec9.png)

However, in commercial applications, such use will expose the source code of configuration files and kernel files, and there is also the risk of tampering.

Is there a solution for this scenario?

**Comment by Iffa-Meah** [comment]
@wang7393 usually in a commercial use case, the whole package will be compiled into an encrypted binary to protect the source code. It's hard to obtain such information unless that person is really good in Reverse Engineering which is still not straightforward as they still need to decrypt the binary. Not to mention that they need to translate an encrypted assembly language into the original src code.

In addition to that, use a variable that only you will understand to call on the config file.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
