### ISSUE TITLE
[Bug] get_property reports wrong device priority order when model is compiled in AUTO mode

### ISSUE THREAD

**Issue by EdjeElectronics** [openvinotoolkit/openvino#14417]
##### System information (version)

- OpenVINO=> 2022.2
- Operating System / Platform => Windows 11 64 Bit
- Compiler => Python runtime installed using PyPI
- Problem classification => n/a

System devices:
- i7-12700 CPU  (CPU)
- Intel UHD Graphic 770 iGPU  (GPU.0)
- Intel Arc A750 dGPU  (GPU.1)

##### Detailed description
When a model is compiled in AUTO mode, the `get_property` method reports device priorities in the reverse order than what is stated in documentation. The Automatic Device Selection page states that devices are reported from high to low, and that the default priority order is dGPU, iGPU, VPU, and CPU. In my case, `get_property` reports `CPU,GPU.0,CPU.1`, which is the reverse of the expected order.

![image](https://user-images.githubusercontent.com/26154245/205744302-3cc4d3c8-fa97-479e-acac-ce3595355c29.png)

##### Steps to reproduce

The problem can be reproduced by running the following Python code. I ran it on a machine with a CPU, iGPU, and dGPU installed. When the code below is run, it will report `MULTI_DEVICE_PRIORITIES: CPU,GPU.0,GPU.1`, which is reverse from the expected priority order. I also uploaded a notebook (forked from `openvino_notebooks`) that can be used to reproduce the problem:
https://github.com/EdjeElectronics/openvino_notebooks/blob/main/notebooks/108-query-device/108-query-device.ipynb

```
# Initialize OpenVINO
from openvino.runtime import Core
ie = Core()

# Download model
base_model_dir = "model"
model_name = "person-detection-0202"
precision = "FP16"
model_path = (
    f"model/intel/{model_name}/{precision}/{model_name}.xml"
)
download_command = f"omz_downloader " \
                   f"--name {model_name} " \
                   f"--precision {precision} " \
                   f"--output_dir {base_model_dir} " \
                   f"--cache_dir {base_model_dir}"
! $download_command

# Compile model in AUTO mode
model = ie.read_model(model=model_path)
compiled_model = ie.compile_model(model, "AUTO")

# Check MULTI_DEVICE_PRIORITIES property
hint_priorities = compiled_model.get_property("MULTI_DEVICE_PRIORITIES")
print('MULTI_DEVICE_PRIORITIES: %s' % hint_priorities)
```

Result: `MULTI_DEVICE_PRIORITIES: CPU,GPU.0,GPU.1`

If I compile the model in MULTI mode with the priority specified as GPU.1 , GPU.0 , CPU , then it does report the correct priority order. This is further proof that AUTO reports the incorrect priority order.
```
compiled_model = ie.compile_model(model, device_name="MULTI:GPU.1,GPU.0,CPU")
hint_priorities = compiled_model.get_property("MULTI_DEVICE_PRIORITIES")
print('MULTI_DEVICE_PRIORITIES: %s' % hint_priorities)
```

Result: `MULTI_DEVICE_PRIORITIES: GPU.1,GPU.0,CPU`

##### Issue submission checklist

 - [X] I report the issue, it's not a question
 - [X] I checked the problem with documentation, FAQ, open issues, Stack Overflow, etc and have not found solution
 - [X] There is reproducer code and related data files: images, videos, models, etc.

**Comment by wangleis** [comment]
@EdjeElectronics Issue had been fixed in master branch. Could you please verify it?

**Comment by EdjeElectronics** [comment]
Hey @wangleis , I have it on my TO DO list to verify this fix. Hoping to verify it this week!

**Comment by EdjeElectronics** [comment]
Hi @wangleis , I cloned the openvino master branch and built it from source. I re-ran the code from my original post, and it is still reporting the incorrect device priority. Here is the output when I run the code:

```
MULTI_DEVICE_PRIORITIES: CPU,GNA,GPU
```

The issue is still not fixed.

**Comment by peterchen-intel** [comment]
@EdjeElectronics Issue was confirmed, I have created an internal ticket 99669 to follow up.

**Comment by peterchen-intel** [comment]
@EdjeElectronics https://github.com/openvinotoolkit/openvino/pull/14754 PR was merged. Please try with master HEAD.

**Comment by ilya-lavrenov** [comment]
Please, reopen if the issue is still here.
Fixed version is 2023.0
