### ISSUE TITLE
RuntimeError: Data inserted into layer ... 0 is nullptr

### ISSUE THREAD

**Issue by qe903121** [openvinotoolkit/openvino#161]
I created a keras model:
```
def test_lstm(input_layer):

    Conv1 = TimeDistributed(Conv2D(64, kernel_size=(3,3), strides=(1,1), use_bias=False, padding='same'), name='conv_1')(input_layer)
    B_CLSTM_last = Bidirectional(ConvLSTM2D(32, kernel_size=(3,3), strides=(1,1), padding="same",return_sequences=False, stateful=False), merge_mode='sum', name='B_CLSTM_last' )(Conv1)
    return B_CLSTM_last

```

convert to .pb file and successfully generated an IR file.
but when i use python api for inference engine :

```
net = IENetwork(model=model_path, weights=weights_path)
exec_net = plugin.load(network=net)
```

it get the error:

```
File "ie_api.pyx", line 395, in openvino.inference_engine.ie_api.IEPlugin.load
 File "ie_api.pyx", line 406, in openvino.inference_engine.ie_api.IEPlugin.load
RuntimeError: Data inserted into layer B_CLSTM_last/while/clip_by_value/Minimum/Max_/Broadcast/:0 is nullptr
```

Is there any solution or recommend? 

Thanks a lot

**Comment by shubha-ramani** [comment]
Dearest @qe903121 
Can you kindly attach your frozen.pb model here and also give me the model optimizer command you used ?
Sorry for the trouble. Looking forward to hearing from you !

Shubha

**Comment by qe903121** [comment]
@shubha-ramani  Thank you for your prompt reply.
All the code used on my attachment. 

[Hsien.zip](https://github.com/opencv/dldt/files/3217954/Hsien.zip)

Thank you again for your help.

Hsien

**Comment by shubha-ramani** [comment]
Dear @qe903121 
I converted your test_lstm2.h5 model by doing the following:
1) used a Keras to frozen pb conversion script to create a frozen.pb
See below:
```
def export_keras_to_tf(input_model, output_model, num_output):
    print('Loading Keras model: ', input_model)

    keras_model = load_model(input_model)

    print(keras_model.summary())

    predictions = [None] * num_output
    predrediction_node_names = [None] * num_output

    for i in range(num_output):
        predrediction_node_names[i] = 'output_node' + str(i)
        predictions[i] = tf.identity(keras_model.outputs[i], name=predrediction_node_names[i])

    sess = K.get_session()

    constant_graph = graph_util.convert_variables_to_constants(sess, sess.graph.as_graph_def(), predrediction_node_names)
    infer_graph = graph_util.remove_training_nodes(constant_graph) 

    graph_io.write_graph(infer_graph, '.', output_model, as_text=False)

```
2) Then used the mo_tf.py  command you gave me:

> python mo_tf.py --input_model frozen.pb  --input input_layer --input_shape [1,3,256,256,1]   --data_type FP32

Which on 2019R1.1 immediately gave me an error at the following node:
B_CLSTM_last/while/Enter_4/TensorIteratorInput_
The error being:
mo.utils.error.Error: Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.CheckForCycle.CheckForCycle'>): Graph contains a cycle. Can not proceed.
 For more information please refer to Model Optimizer FAQ (<INSTALL_DIR>/deployment_tools/documentation/docs/MO_FAQ.html), question #97.

3) Next I used the technique called [model cutting](http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Cutting_Model.html) to chop off the model at using the following command (and it successfully generated IR)

> python "c:\Program Files (x86)\IntelSWTools\openvino_2019.1.148\deployment_tools\model_optimizer\mo_tf.py" --input_model "c:\users\sdramani\Downloads\test_lstm2.h5.pb" --input input_layer --input_shape [1,3,256,256,1]   --data_type FP32 --log_level DEBUG --output "B_CLSTM_last/while/Enter_4"

4)Ran the Python classification sample and got an error:
python "c:\Program Files (x86)\IntelSWTools\openvino_2019.1.148\deployment_tools\inference_engine\samples\python_samples\classification_sample\classification_sample.py" -m test_lstm2.h5.xml -i c:\users\sdramani\Downloads\pics\horse.bmp -l "c:\users\sdramani\Documents\Intel\OpenVINO\inference_engine_samples_build\intel64\Release\cpu_extension.dll"
[ INFO ] Loading network files:
        test_lstm2.h5.xml
        test_lstm2.h5.bin
[ ERROR ] Following layers are not supported by the plugin for specified device CPU:
 B_CLSTM_last/while/Enter_4
[ ERROR ] Please try to specify cpu extensions library path in sample's command line parameters using -l or --cpu_extension command line argument

By the way, I got a very similar error with the IR you generated too.  I am curious anyway - how did you generate that IR ? Did you not get the graph cycle error ? If you can re-build that model this time without containing a graph cycle, it may work. LSTM is definitely supported.

Looking forward to hearing from you here. 

Sincerely,

Shubha

**Comment by qe903121** [comment]
@shubha-ramani 



 I used the below code to convert a pb file.

> https://github.com/HsinM/OpenVINO-NCS/tree/master/win_linux_code

and successfully converted files.

then used mo_tf.py 
`python mo_tf.py --input_model test_lstm2_tf.pb  --input input_layer --input_shape [1,3,256,256,1]   --data_type FP32`
It didn't raise any error, and got the IR file.

but if i used your conversion script and used the same command to execute mo_ty.py, that will got the same error.  So, maybe there is an problem in conversion program.

I have another question.
I followed your operate, and got the IR file. 
next, configure my NCS2 and run python api for inference engine
```
net = IENetwork(model=model_path, weights=weights_path)
exec_net = plugin.load(network=net)
plugin = IEPlugin(device="MYRIAD")
exec_net = plugin.load(network=net)
```
got the error:
```
  File "ie_api.pyx", line 395, in openvino.inference_engine.ie_api.IEPlugin.load
  File "ie_api.pyx", line 406, in openvino.inference_engine.ie_api.IEPlugin.load
RuntimeError: [VPU] Cannot convert layer "B_CLSTM_last/while/Enter_4" due to unsupported layer type "Enter"
```
Is the device(NCS2) unsupported this layer?

Thanks a lot


Hsien

**Comment by shubha-ramani** [comment]
Dear @qe903121 
OK. The main difference between that github's h5_to_pb_to_vino_file.py and my version is that he's saving ALL the models into the frozen.pb while I am saving just 1. I was able to generate IR successfully using the model cutting approach, though, as you saw above.

Now it makes sense that LSTM would not work on MYRIAD, because [Supported Devices](http://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_Supported_Devices.html) document says that LSTM is not supported on VPU just yet.

But nevertheless, you helped to root-cause a bug @qe903121 because I wasn't even trying to run on NCS2. I got the error running on CPU.

Hope it helps. Thanks for your patience most of all and thanks for using OpenVino !

Shubha

**Comment by qe903121** [comment]
@shubha-ramani 
I appreciate very much that your assistance.
It's great to discuss this issue with you.

Gratefully yours
Hsien

**Comment by shubha-ramani** [comment]
Dear @qe903121 ,
I enjoy discussing technical issues with customers too ! I love this job ! Thank you for using OpenVino and for being patient with us. The Intel OpenVino team is working hard every day to give customers what they need. Did you see that the VPU Plugin is now open-sourced ? Please take a look ! Maybe you can figure out a way to add LSTM yourself (I know it's a big project but just saying...maybe you have an interest, or loads of free time).

Shubha

**Comment by qe903121** [comment]
@shubha-ramani 
Wow! hanks for your effort!  you're awesome !
I think It is a big challenge to add LSTM myself , but worth a try !
Before that, I should research VPU Plugin document in detail.
Thanks for your recommendation that is a good method for training my programming.

Hsien

**Comment by wumeng2** [comment]
> Dear @qe903121
> OK. The main difference between that github's h5_to_pb_to_vino_file.py and my version is that he's saving ALL the outputs into the frozen.pb while I am saving just 1. I was able to generate IR successfully using the model cutting approach, though, as you saw above.
> 
> Now it makes sense that LSTM would not work on MYRIAD, because [Supported Devices](http://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_Supported_Devices.html) document says that LSTM is not supported on VPU just yet.
> 
> But nevertheless, you helped to root-cause a bug @qe903121 because I wasn't even trying to run on NCS2. I got the error running on CPU so I will definitely file a bug on this issue (for CPU).
> 
> Hope it helps. Thanks for your patience most of all and thanks for using OpenVino !
> 
> Shubha

Dear @shubha-ramani ，
First of all, thank you for your excellent work. I also build a lstm model in keras， and suceed to convert H5 to pb, then to IR, but when i deploy IR model using opencv4.1.1 and openvino_2019.1.144 for cpu, I get some same error message " what():  OpenCV(4.1.1) /home/py/opencv/opencv-4.1.1-dynamic/modules/dnn/src/op_inf_engine.cpp:477: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: Data inserted into layer lstm1/while/clip_by_value/Minimum/Max_/Broadcast/:0 is nullptr in function 'initPlugin'". 
 after this, I using opencv4.2.0 and openvino_2020.1.023, and get some different error message "what():  OpenCV(4.2.0) /home/py/download/opencv-4.2.0/modules/dnn/src/op_inf_engine.cpp:774: error: (-2:Unspecified error) Failed to initialize Inference Engine backend (device = CPU): Cannot create internal buffer. Buffer can be overrun. in function 'initPlugin'",  Hope to get your advice.

thank you
mengmeng

**Comment by ilyachur** [comment]
Hi @wumeng2,

If you get an error: "Cannot create internal buffer. Buffer can be overrun." it means that something wrong with weights for you model.
Please check that you have a correct shapes for weights data in your model because this error message said that calculated shapes is bigger that size of data which CPU plugin got from the model.

@qe903121 Can you please confirm that the original issue was resolved?

**Comment by wumeng2** [comment]
Dear @ilyachur ,
Thank you for your prompt reply.  Inference using h5 model in python is ok. I just convert h5 to IR, then meet this problem in c++. before, I have successful deployed object detection model by this way. this is the first try of deployment of Lstm Network.  the weight shape and input shape  is ok. mayebe the problem is related to the network structure.  I will try a tiny and simple lstm model to test again.

Thank you again
mengmeng

**Comment by ilyachur** [comment]
@wumeng2 Maybe you get incorrect IR file and some weights in this file have incorrect size.

@lazarevevgeny Can you advice something to check?

**Comment by wumeng2** [comment]
Dear @ilyachur,
I try a tiny model, but still get the same error message "" what(): OpenCV(4.1.1) /home/py/opencv/opencv-4.1.1-dynamic/modules/dnn/src/op_inf_engine.cpp:477: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: Data inserted into layer lstm1/while/clip_by_value/Minimum/Max_/Broadcast/:0 is nullptr in function 'initPlugin'"".

code of model is listed below.
`from keras.models import Sequential
from keras.layers import LSTM, Dense
import numpy as np

data_dim = 16
timesteps = 8
num_classes = 10

# expected input data shape: (batch_size, timesteps, data_dim)
model = Sequential()
model.add(LSTM(32, return_sequences=True,
               input_shape=(timesteps, data_dim)))  # returns a sequence of vectors of dimension 32
model.add(LSTM(32, return_sequences=True))  # returns a sequence of vectors of dimension 32
model.add(LSTM(32))  # return a single vector of dimension 32
model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

# Generate dummy training data
x_train = np.random.random((1000, timesteps, data_dim))
y_train = np.random.random((1000, num_classes))

# Generate dummy validation data
x_val = np.random.random((100, timesteps, data_dim))
y_val = np.random.random((100, num_classes))

model.fit(x_train, y_train,
          batch_size=64, epochs=5,
          validation_data=(x_val, y_val))

model.save("test-lstm.h5")`

I notice this layer in xml file.
`					<layer id="7" name="lstm_1/while/clip_by_value_2/Minimum/Max_/Broadcast/" precision="FP32" type="Tile">
						<data axis="1" tiles="32"/>
						<input>
							<port id="0">
								<dim>1</dim>
								<dim>1</dim>
							</port>
						</input>
						<output>
							<port id="1">
								<dim>1</dim>
								<dim>32</dim>
							</port>
						</output>
					</layer>`
I am curious how the lstm in openvino Pre-Trained Models is deployed successfully. What details should be noticed when i do it by myself.
 thank you

**Comment by ilyachur** [comment]
@wumeng2 The error like "Data inserted into layer lstm1/while/clip_by_value/Minimum/Max_/Broadcast/:0 is nullptr" can be caused by different reasons, like incorrect model or bugs on conversion or plugin sides.

@dkurt What version of Inference Engine is used in the OpenCV(4.1.1)?

**Comment by dkurt** [comment]
> OpenCV(4.1.1)
Please test the latest OpenCV and 
Inference Engine.

**Comment by ilyachur** [comment]
@wumeng2 Do you have any update? 
Did you try the latest OpenCV?

**Comment by wumeng2** [comment]
@ilyachur I am on vacation now and  have not had a try. After I try latest version, I will reply you.

**Comment by ilyachur** [comment]
@wumeng2 ok, thank you!

**Comment by wumeng2** [comment]
> @wumeng2 ok, thank you!

Dear @ilyachur 
I try opencv4.3 and opencv4.4 and openvino2020.3.194, The tiny model of lstm above worked, but my model still get some error message "
what():  OpenCV(4.4.0) /home/py/downloads/opencv-4.4.0/modules/dnn/src/ie_ngraph.cpp:692: error: (-2:Unspecified error) Failed to initialize Inference Engine backend (device = CPU): Cannot create internal buffer. Buffer can be overrun. in function 'initPlugin' ". mayebe the problem is related to the network structure.
Thank you!

**Comment by sahira-rizvi** [comment]
Closing, feel free to re-open or create a new issue if additional assistance is needed.

Sincerely,
Sahira
