### ISSUE TITLE
[Bug]: Crash at InferRequest::set_tensor in Openvino 2023.0.1

### ISSUE THREAD

**Issue by Dush27** [openvinotoolkit/openvino#19531]
### OpenVINO Version

tag 2023.0.1

### Operating System

Windows System

### Device used for inference

CPU

### Framework

None

### Issue description

System information (version)
OpenVINO Source=> Custom built 2023.0.1 for Electron node addon
OpenVINO Version=> 2023.0.1
Operating System / Platform => Windows 10
Compiler => Visual Studio
Problem classification => Crash
Device use: => CPU
Framework => Electron

[Crash.zip](https://github.com/openvinotoolkit/openvino/files/12495243/Crash.zip)

![Openvino_2023 0 1 crash](https://github.com/openvinotoolkit/openvino/assets/114069851/0d604b94-b288-406c-8146-0ef451fb83e8)

Attached DxDiag information and crashdump where this issue was observed.
NOTE: This was observed only once.

### Issue submission checklist

- [X] I report the issue. It's not a question
- [X] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found the solution
- [x] There is reproducer code and related data files such as images, videos, models, etc.

**Comment by ilyachur** [comment]
@Dush27 Could you try to reproduce the issue on the latest master?

**Comment by Dush27** [comment]
This issue happened only once even with 2023.0.1. 
Based on the stack trace, you mean it is fixed in latest master and hence you are asking to try with it?

**Comment by ilyachur** [comment]
@Dush27 Yes if you can try the latest master, it will be great.
We have changed the internal API and maybe migration to the latest master could help to resolve the issue.

**Comment by Dush27** [comment]
@ilyachur, Can you confirm if the fix is available with 2023.0.2 tag so that I can check and get back ?

**Comment by ilyachur** [comment]
No, `2023.0.2` release doesn't contain these changes

**Comment by Dush27** [comment]
Ok thanks. We will try with master then. Also can you please confirm when will 2023.0.3 release will be available with this fix?

**Comment by ilyachur** [comment]
The next release will be [2023.1](https://github.com/openvinotoolkit/openvino/tree/releases/2023/1), and I hope it should also contain the fix.
But in case if issue is still here, we need to have deeper analysis what happens, because right now all tests are passing on all platforms...

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen to ask any questions related to this topic if issue persists.
