### ISSUE TITLE
[Bug]: multiple cache file generated for the same model

### ISSUE THREAD

**Issue by jules-ai** [openvinotoolkit/openvino#31672]
### OpenVINO Version

2025.2

### Operating System

Windows System

### Device used for inference

CPU

### Framework

None

### Issue description

I noticed that on the same device, using exactly the same inference configuration (`CPU`, `LATENCY` mode, etc.), OpenVINO sometimes produces multiple cache files (`.blob`) for the same model when calling `compile_model`.

After comparing the cache files generated for the same model, I observed three cases:
- A. Every byte is identical.
- B. About 99% of the content is identical, with only a very small number of bytes differing.
- C. Around 1/8 of the bytes are different.

Could you please confirm whether this is a bug?
If this is not a bug but an intentional design choice, would it be possible to optimize the behavior?
In my opinion, at least in case A, where the contents are completely identical, storing duplicate cache files seems inefficient.

### Relevant log output

```shell

```

### Issue submission checklist

- [x] I'm reporting an issue. It's not a question.
- [x] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [x] There is reproducer code and related data files such as images, videos, models, etc.

**Comment by DipayanDasgupta** [comment]
.take

**Comment by DipayanDasgupta** [comment]
Hello @jules-ai and maintainers,
I wanted to follow up on this issue. I created a regression test script that repeatedly compiles a model to a clean cache directory and then checks for file duplication using SHA256 hashes.
The script shows that on the latest master commit (<f705706fbceca2fade8daa685f51bfacc730744f>), the issue is no longer reproducible. The test successfully generated a single, unique cache file after 10 compilations.
This suggests the bug was likely fixed by a recent commit between when the issue was reported and now. Based on this, it seems this issue can be closed.
If you'd like, I can create a new Pull Request to add my regression test script to the repository to help prevent this from happening in the future.

**Comment by DipayanDasgupta** [comment]
Hello @jules-ai and maintainers,
I investigated this issue and can confirm that it appears to be fixed on the latest master branch.
I created a regression test script that repeatedly compiles the same model to a clean cache directory and then validates the uniqueness of the generated .blob files by checking their SHA256 hashes. When running this test against the latest master, it successfully produces only one unique cache file, confirming the fix.
To ensure this bug doesn't reappear in the future, I have submitted Pull Request #31702 to add this script as a permanent regression test.
Based on these findings, I believe this issue can now be closed. Thank you, @jules-ai, for the excellent bug report.

**Comment by jules-ai** [comment]
I re-compiled with the latest code(dacd71e765c6396ef725f08c35009d6cfbcdb830 for now) on master and the issue still exists. This issue occurred in my C++ reproduction. It happens when the process exits and is restarted, and so far I haven’t found any other patterns. Probably it’s just the test code cannot reproduce this issue.

**Comment by jules-ai** [comment]
@DipayanDasgupta Do you have any news?

**Comment by jules-ai** [comment]
any updates?
