### ISSUE TITLE
Error trying to build dldt/inference engine for armv7

### ISSUE THREAD

**Issue by ralphjy** [openvinotoolkit/openvino#810]
I have gone through the basic instructions https://software.intel.com/content/www/us/en/develop/articles/arm-sbc-and-ncs2.html
to install OpenVino on a PYNQ-Z2 that uses Ubuntu on an Arm7 32 bit processor.

I've updated CMake, installed OpenCV and updated dependencies.

When I try to build:
cmake -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_MKL_DNN=OFF \
    -DENABLE_CLDNN=OFF \
    -DENABLE_GNA=OFF \
    -DENABLE_SSE42=OFF \
    -DTHREADING=SEQ \
    ../..

I am getting the following error:
Run Build Command:"/usr/bin/make" "cmTC_669ce/fast"
/usr/bin/make -f CMakeFiles/cmTC_669ce.dir/build.make CMakeFiles/cmTC_669ce.dir/build
make[1]: Entering directory '/home/xilinx/dldt/inference-engine/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_669ce.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_669ce.dir/CheckSymbolExists.c.o   -c /home/xilinx/dldt/inference-engine/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_669ce
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_669ce.dir/link.txt --verbose=1
/usr/bin/cc      CMakeFiles/cmTC_669ce.dir/CheckSymbolExists.c.o  -o cmTC_669ce 
CMakeFiles/cmTC_669ce.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x2c): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_669ce.dir/build.make:97: recipe for target 'cmTC_669ce' failed
make[1]: *** [cmTC_669ce] Error 1
make[1]: Leaving directory '/home/xilinx/dldt/inference-engine/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_669ce/fast' failed
make: *** [cmTC_669ce/fast] Error 2

I suspect that I'm missing a library but am not sure how to determine which one.

**Comment by avitial** [comment]
Hi @ralphjy which version of dldt are you trying to build? From which directory are you running CMake command? Make sure you have set the _OpenCV_DIR_, the guide specifies export `OpenCV_DIR=/usr/local/opencv4` but it could also be `export OpenCV_DIR=/usr/local/lib` or the specific location of your OpenCV install path. Also which Ubuntu version does your board use?

**Comment by ralphjy** [comment]
Hi @avitial  - thanks for the response

From InferenceEngineConfig-version.cmake it is InferenceEngine_VERSION 2.1.0
I did not specify that so I guess it's the latest (cloned yesterday)?

I am running CMake from /home/xilinx/dldt/inference-engine/build
I had to modify the cmake option to read from the dldt directory (i.e. ../..)

I did not have the correct export - apparently OpenCV installed to /usr/local/share/opencv4
When I fixed the install path I got a different but similar error.
I've attached the CMakeError.log
[CMakeError.log](https://github.com/openvinotoolkit/openvino/files/4748643/CMakeError.log)

The board is using a derivative of Ubuntu 18.04.
xilinx@pynq:/usr/local$ lsb_release -a
No LSB modules are available.
Distributor ID: pynqlinux
Description:    PYNQ Linux, based on Ubuntu 18.04
Release:        v2.5
Codename:       glasgow

Ralph

**Comment by avitial** [comment]
@ralphjy  the issue seems to be related to miss fetching repo submodules, please try the following and re-run your CMake command:
`cd /home/xilinx/dldt/inference-engine`
`git submodule update --init --recursive`

Let me know if issue persists, I hope the above command resolves it. 

~Luis

**Comment by ralphjy** [comment]
Hi @avitial ,
Thanks, that fixed the CMake error.  The problem was that the instructions that I am following did not have the "--" in front of --init and I missed that because it did not give me an error.

I am very close to successfully installing but just ran into another error building the benchmark_app,

[ 97%] Building CXX object inference-engine/samples/benchmark_app/CMakeFiles/benchmark_app.dir/utils.cpp.o
[ 97%] Linking CXX executable ../../../../../bin/armv7l/Release/benchmark_app
/usr/bin/arm-linux-gnueabihf-ld: CMakeFiles/benchmark_app.dir/utils.cpp.o: undefined reference to symbol '_ZNK2cv8FileNode4sizeEv'
//usr/lib/arm-linux-gnueabihf/libopencv_core.so.3.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
inference-engine/samples/benchmark_app/CMakeFiles/benchmark_app.dir/build.make:134: recipe for target '../../bin/armv7l/Release/benchmark_app' f
ailed
make[2]: *** [../../bin/armv7l/Release/benchmark_app] Error 1
CMakeFiles/Makefile2:4869: recipe for target 'inference-engine/samples/benchmark_app/CMakeFiles/benchmark_app.dir/all' failed
make[1]: *** [inference-engine/samples/benchmark_app/CMakeFiles/benchmark_app.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by avitial** [comment]
This looks like an issue with opencv library, if you have multiple versions of OpenCV please point OpenCV_DIR to the correct one.

Did you build and install opencv from source? If you followed same instructions as stated [here](https://software.intel.com/content/www/us/en/develop/articles/arm64-sbc-and-ncs2.html), try pointing OpenCV_DIR to /usr/local/lib (`export OpenCV_DIR=/usr/local/lib`) and re-run make command. Let me know the results of this.

~Luis

**Comment by avitial** [comment]
@ralphjy lets try the following:

- Set `OpenCV_DIR` environment variable to where the `OpenCVConfig.cmake` file of you custom OpenCV build is located. This location may be similar to `/home/user/opencv/build` or `/usr/local/lib/cmake/opencv4`
- Add `-DENABLE_OPENCV=OFF` option to disable package automatic downloading for CMake-based build script for Inference Engine
- Rebuild dldt package with `make -j4`

For more information on custom OpenCV builds for Inference Engine see [here](https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md#use-custom-opencv-builds-for-inference-engine). Hope the steps above address the issue, let me know your results.

**Comment by ralphjy** [comment]
@avitial - thanks for all your help but I 'm going to give up trying to install OpenVINO on this board.  I tried starting with a new OS image and removed the existing cmake and opencv installations before going through the install instructions.  It gets pretty far, but it still can't build the examples.

Here is where it failed:
[ 98%] Built target opencv_c_wraper
[ 98%] Linking CXX executable ../../../../../../../bin/armv7l/Release/object_detection_sample_ssd_c
../../../../../../../bin/armv7l/Release/lib/libopencv_c_wraper.so: undefined reference to `cv::fastFree(void*)'
../../../../../../../bin/armv7l/Release/lib/libopencv_c_wraper.so: undefined reference to `cv::resize(cv::_InputArray const&, cv::_OutputArray c
onst&, cv::Size_<int>, double, double, int)'
../../../../../../../bin/armv7l/Release/lib/libopencv_c_wraper.so: undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char
_traits<char>, std::allocator<char> > const&, int)'
../../../../../../../bin/armv7l/Release/lib/libopencv_c_wraper.so: undefined reference to `cv::imwrite(std::__cxx11::basic_string<char, std::cha
r_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
../../../../../../../bin/armv7l/Release/lib/libopencv_c_wraper.so: undefined reference to `cv::Mat::updateContinuityFlag()'
../../../../../../../bin/armv7l/Release/lib/libopencv_c_wraper.so: undefined reference to `cv::error(int, std::__cxx11::basic_string<char, std::
char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)'
../../../../../../../bin/armv7l/Release/lib/libopencv_c_wraper.so: undefined reference to `cv::Mat::deallocate()'
collect2: error: ld returned 1 exit status
inference-engine/ie_bridges/c/samples/object_detection_sample_ssd/CMakeFiles/object_detection_sample_ssd_c.dir/build.make:90: recipe for target
'../../bin/armv7l/Release/object_detection_sample_ssd_c' failed
make[2]: *** [../../bin/armv7l/Release/object_detection_sample_ssd_c] Error 1
CMakeFiles/Makefile2:6447: recipe for target 'inference-engine/ie_bridges/c/samples/object_detection_sample_ssd/CMakeFiles/object_detection_samp
le_ssd_c.dir/all' failed
make[1]: *** [inference-engine/ie_bridges/c/samples/object_detection_sample_ssd/CMakeFiles/object_detection_sample_ssd_c.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

This particular board has a single Arm A9 core so the build process takes for the inference-engine takes about 12 hours so it probably isn't worth the time trying to figure this out.  I had hoped that this would have been more straightforward but it is becoming too painful to try more experiments.  I did try your suggestions.  Something about my configuration just doesn't work with the installation process.  Somehow the opencv libraries don't seem to link properly.

Thanks for all your help - you can go ahead and close this.

Ralph
